#
# Makefile to use with GLFW+emscripten
# See https://emscripten.org/docs/getting_started/downloads.html
# for installation instructions.
#
# This Makefile assumes you have loaded emscripten's environment.
# (On Windows, you may need to execute emsdk_env.bat or encmdprompt.bat ahead)
#
# Running `make -f Makefile.emscripten` will produce three files:
#  - web/index.html
#  - web/index.js
#  - web/index.wasm
#
# All three are needed to run the demo.

CC = emcc
CXX = em++
WEB_DIR = web
EXE = $(WEB_DIR)/index.html
IMGUI_DIR = ../..
SOURCES = main.cpp app.cpp main_window.cpp partial_network_stream.cpp stream_parser.cpp tokens.cpp tree_node.cpp tree_node_collection.cpp network_stream.cpp
SOURCES += $(IMGUI_DIR)/imgui.cpp $(IMGUI_DIR)/imgui_demo.cpp $(IMGUI_DIR)/imgui_draw.cpp $(IMGUI_DIR)/imgui_tables.cpp $(IMGUI_DIR)/imgui_widgets.cpp
SOURCES += $(IMGUI_DIR)/backends/imgui_impl_glfw.cpp $(IMGUI_DIR)/backends/imgui_impl_opengl3.cpp

SOURCES += $(IMGUI_DIR)/misc/freetype/imgui_freetype.cpp

SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/autofit/autofit.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftbase.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftbbox.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftbdf.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftbitmap.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftcid.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftfstype.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftgasp.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftglyph.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftgxval.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftinit.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftmm.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftotval.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftpatent.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftpfr.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftstroke.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftsynth.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/fttype1.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftwinfnt.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/bdf/bdf.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/bzip2/ftbzip2.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/cache/ftcache.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/cff/cff.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/cid/type1cid.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/gzip/ftgzip.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/lzw/ftlzw.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/pcf/pcf.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/pfr/pfr.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/psaux/psaux.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/pshinter/pshinter
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/psnames/psnames.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/raster/raster.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/sdf/sdf.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/sfnt/sfnt.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/smooth/smooth.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/truetype/truetype
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/type1/type1.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/type42/type42.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/winfonts/winfnt.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftsystem.c
SOURCES += $(IMGUI_DIR)/misc/depends/freetype/src/base/ftdebug.c

OBJS = $(addsuffix .o, $(basename $(notdir $(SOURCES))))
UNAME_S := $(shell uname -s)
CPPFLAGS =
LDFLAGS =
EMS =

##---------------------------------------------------------------------
## EMSCRIPTEN OPTIONS
##---------------------------------------------------------------------

# ("EMS" options gets added to both CPPFLAGS and LDFLAGS, whereas some options are for linker only)
EMS += -s DISABLE_EXCEPTION_CATCHING=1
LDFLAGS += -s USE_GLFW=3 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s NO_EXIT_RUNTIME=0 -s ASSERTIONS=1 -s "EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']" -s STACK_SIZE=1gb

# Build as single file (binary text encoded in .html file)
#LDFLAGS += -sSINGLE_FILE

# Uncomment next line to fix possible rendering bugs with Emscripten version older then 1.39.0 (https://github.com/ocornut/imgui/issues/2877)
#EMS += -s BINARYEN_TRAP_MODE=clamp
#EMS += -s SAFE_HEAP=1    ## Adds overhead

# Emscripten allows preloading a file or folder to be accessible at runtime.
# The Makefile for this example project suggests embedding the misc/fonts/ folder into our application, it will then be accessible as "/fonts"
# See documentation for more details: https://emscripten.org/docs/porting/files/packaging_files.html
# (Default value is 0. Set to 1 to enable file-system and include the misc/fonts/ folder as part of the build.)
USE_FILE_SYSTEM ?= 1
ifeq ($(USE_FILE_SYSTEM), 0)
LDFLAGS += -s NO_FILESYSTEM=1
CPPFLAGS += -DIMGUI_DISABLE_FILE_FUNCTIONS
endif
ifeq ($(USE_FILE_SYSTEM), 1)
LDFLAGS += --no-heap-copy --preload-file ../../misc/fonts@/fonts
endif

##---------------------------------------------------------------------
## FINAL BUILD FLAGS
##---------------------------------------------------------------------

CPPFLAGS += -I$(IMGUI_DIR) -I$(IMGUI_DIR)/backends

CPPFLAGS += -I$(IMGUI_DIR)/misc/freetype

CPPFLAGS += -I$(IMGUI_DIR)/misc/freetype/include
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype/include
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype/include/freetype
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype/config
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype/internal
CPPFLAGS += -I$(IMGUI_DIR)/misc/depends/freetype/src/autofit

CPPFLAGS += -DFT2_BUILD_LIBRARY


#CPPFLAGS += -g
CPPFLAGS += -Wall -Wformat -Os $(EMS)
#LDFLAGS += --shell-file ../libs/emscripten/shell_minimal.html
LDFLAGS += --shell-file ./index.html
LDFLAGS += $(EMS)

##---------------------------------------------------------------------
## BUILD RULES
##---------------------------------------------------------------------

%.o:%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o:$(IMGUI_DIR)/%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o:$(IMGUI_DIR)/backends/%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o:$(IMGUI_DIR)/misc/freetype/%.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

%.o:$(IMGUI_DIR)/misc/depends/freetype/src/*/%.c
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

all: $(EXE)
	@echo Build complete for $(EXE)

$(WEB_DIR):
	mkdir $@

serve: all
	python3 -m http.server -d $(WEB_DIR)

$(EXE): $(OBJS) $(WEB_DIR)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS) -s EXPORTED_FUNCTIONS="['_main','_processFileBytes']"

clean:
	rm -rf $(OBJS) $(WEB_DIR)
